# -*- coding: utf-8 -*-
#
# FFTHomPy documentation build configuration file, created by
# sphinx-quickstart on Fri Jan 23 17:52:11 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# extensions = ['sphinx.ext.mathjax']
extensions = ['sphinx.ext.pngmath']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'FFTHomPy'
copyright = u'2015, Jaroslav Vondřejc'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.0'
# The full version, including alpha/beta/rc tags.
release = '1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'FFTHomPydoc'


# -- Options for LaTeX output ---------------------------------------------

ADDITIONAL_PREAMBLE = r"""
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{amssymb}
\usepackage{mathrsfs}
\usepackage{amsfonts}
\usepackage{bbold}

\newcommand{\cb}[1]{\V{U}^{(#1)}}

\newcommand{\set}[1]{\mathbb{#1}}
\newcommand{\M}[1]{\mat{#1}}
\newcommand{\MB}[1]{\boldsymbol{\mat{#1}}}
\newcommand{\mat}[1]{\mathsf{#1}} %matrix
\newcommand{\V}[1]{\boldsymbol{#1}}
\newcommand{\T}[1]{\boldsymbol{#1}}
\newcommand{\ol}[1]{\overline{#1}}
\newcommand{\ul}[1]{\underline{#1}}
\newcommand{\oul}[1]{\overline{\underline{#1}}}
\newcommand{\uol}[1]{\oul{#1}}
\newcommand{\mac}[1]{^{(#1)}}
\newcommand{\mmac}[1]{{(#1)}}
\newcommand{\sub}[1]{^{#1}}
\newcommand{\incl}[1]{_{(#1)}}
\newcommand{\iter}[1]{_{(#1)}}
\newcommand{\TA}{\boldsymbol{A}}
\newcommand{\Vx}{{\boldsymbol{x}}}
\newcommand{\VN}{{\boldsymbol{N}}}
\newcommand{\Vm}{\boldsymbol{m}}
\newcommand{\Vn}{{\V{n}}}
\newcommand{\Vk}{{\boldsymbol{k}}}
\newcommand{\Vq}{{\V{q}}}
\newcommand{\Vl}{{\V{l}}}
\newcommand{\Vr}{\V{r}}
\newcommand{\Vs}{\V{s}}
\newcommand{\Vh}{{\V{h}}}
\newcommand{\Vo}{{\V{0}}}
\newcommand{\Vxi}{\V{\xi}}
\newcommand{\VP}{{\V{P}}}
\newcommand{\VY}{{\V{Y}}}

\newcommand{\MBA}{\ensuremath{\MB{A}}}

\newcommand{\xNd}{\set{N}^d}
\newcommand{\Zd}{\set{Z}^d}
\newcommand{\ZdmO}{\set{Z}^d \backslash \{\T{0}\}}
\newcommand{\NOmO}{\set{N}^{\dime}_{0} \backslash \{\T{0}\}}
\newcommand{\ZN}{\set{Z}_{\VN}}
\newcommand{\ZNdr}{\mathring{\set{Z}}^d_{\VN}}
\newcommand{\ZtNd}{\set{Z}^d_{\tVN}}
\newcommand{\ZtNrd}{\set{Z}^d_{\tVNr}}
\newcommand{\ZNd}{\set{Z}^d_{\VN}}
% \newcommand{\ZNNd}{\xZ^d_{\tVNr}}
\newcommand{\ZMd}{\xZ^d_{\V{M}}}
\newcommand{\ZPd}{\xZ^d_{\V{P}}}
\newcommand{\xVN}{\set{V}_\VN}
\newcommand{\xWN}{\set{W}_\VN}
\newcommand{\xS}{\set{S}}
\newcommand{\xSd}{\set{S}^d}

\newcommand{\puc}{\mathcal{Y}}
\newcommand{\lpuc}{Y}
\newcommand{\pVN}{\meas{\VN}}
\newcommand{\ptVN}{\meas{\tVN}}
\newcommand{\ptVNr}{\meas{\tVNr}}
\newcommand{\pVM}{\meas{\VM}}
\newcommand{\pVP}{\meas{\VP}}
\newcommand{\per}{\#}
\newcommand{\eff}{{\mathrm{H}}}
\newcommand{\full}{{\mathrm{full}}}
\newcommand{\odd}{{\mathrm{odd}}}
\newcommand{\dime}{d}


\newcommand{\xR}{\set{R}}
\newcommand{\xN}{\set{N}}
\newcommand{\xZ}{\set{Z}}
\newcommand{\xC}{\set{C}}
\newcommand{\xRd}{{\set{R}^{d}}}
\newcommand{\xCd}{\set{C}^{d}}
\newcommand{\xCdN}{\set{C}^{d\times\VN}}
\newcommand{\xRdd}{\set{R}^{d\times d}}
\newcommand{\xCdd}{\set{C}^{d\times d}}
\newcommand{\xRdN}{\xR^{d\times \VN}}
\newcommand{\xRdM}{\xR^{d\times \VM}}
\newcommand{\xCdM}{\xC^{d\times \VM}}
\newcommand{\xRdtN}{{\xR^{d\times\tVN}}}
\newcommand{\xRdtNr}{{\xR^{d\times(\tVNr)}}}
\newcommand{\xRddNN}{\xR^{d\times d\times\VN\times\VN}}
\newcommand{\xCddNN}{\xR^{d\times d\times\VN\times\VN}}
\newcommand{\xRddtNN}{{\xR^{d\times d\times\tVN\times\tVN}}}
\newcommand{\xRddspd}{\set{R}_{\mathrm{spd}}^{d\times d}}
\newcommand{\xMN}{\bigl[\set{R}^{d\times\VN}\bigr]^2}
\newcommand{\xMM}{\bigl[\set{R}^{d\times\VM}\bigr]^2}
\newcommand{\xMtN}{\bigl[\set{R}^{d\times\tVN}\bigr]^2}
\newcommand{\xMtNr}{\bigl[\set{R}^{d\times(\tVNr)}\bigr]^2}
\newcommand{\xhMN}{\bigl[\set{C}^{d\times\VN}\bigr]^2}
\newcommand{\xhMM}{\bigl[\set{C}^{d\times\VM}\bigr]^2}
\newcommand{\xhMtN}{\bigl[\set{C}^{d\times(\tVN)}\bigr]^2}
\newcommand{\xXN}{\xRdN}
\newcommand{\xXM}{\xRdM}
\newcommand{\xhXM}{\xCdM}
\newcommand{\xXtNr}{\xR^{d\times(\tVNr)}}
\newcommand{\xXtN}{\xR^{d\times\tVN}}
\newcommand{\xhXN}{\set{C}^{d\times\VN}}
\newcommand{\xX}{\set{X}}
\newcommand{\hX}{\hat{\set{X}}}
\newcommand{\cH}{\mathscr{H}}

\newcommand{\xUN}{\set{U}_\VN}
\newcommand{\xEN}{\set{E}_\VN}
\newcommand{\xJN}{\set{J}_\VN}
\newcommand{\xENM}{\set{E}_{\VN,\VM}}
\newcommand{\xJNM}{\set{J}_{\VN,\VM}}
\newcommand{\xENF}{\widehat{\set{E}}_\VN}
\newcommand{\xJNF}{\widehat{\set{J}}_\VN}
\newcommand{\xUtN}{\set{U}_{\tVN}}
\newcommand{\xEtN}{\set{E}_{\tVN}}
\newcommand{\xJtN}{\set{J}_{\tVN}}
\newcommand{\xEtNr}{\set{E}_{\tVNr}}
\newcommand{\xJtNr}{\set{J}_{\tVN}}
\newcommand{\xENapp}{\tilde{\set{E}}_\VN}
\newcommand{\xJNapp}{\tilde{\set{J}}_\VN}
\newcommand{\cT}{\mathscr{T}}
\newcommand{\cTN}{\cT_\VN}
\newcommand{\cTtN}{\cT_\tVNr}
\newcommand{\cTtNd}{\cT^d_\tVN}
\newcommand{\cTtNrd}{\cT^d_\tVNr}
\newcommand{\cTNt}{\tilde{\cT}_\VN}
\newcommand{\cTNd}{\cT_\VN^d}
\newcommand{\cTNtd}{\tilde{\cT}_\VN^d}
\newcommand{\xV}{\set{V}}
\newcommand{\xW}{\set{W}}
\newcommand{\cV}{\mathscr{V}}
\newcommand{\cW}{\mathscr{W}}
\newcommand{\xNk}{\Vx^{\Vk}_\VN}
\newcommand{\xPk}{\Vx^{\Vk}_\VP}
\newcommand{\xNm}{\Vx^{\Vm}_\VN}

\newcommand{\ep}{\ensuremath{\varepsilon}}
\newcommand{\del}{\ensuremath{\delta}}
\newcommand{\alp}{\ensuremath{\alpha}}
\newcommand{\bet}{\ensuremath{\beta}}
\newcommand{\gam}{\ensuremath{\gamma}}
\newcommand{\lam}{\ensuremath{\lambda}}

\DeclareMathOperator{\rect}{rect}
\DeclareMathOperator{\tri}{tri}
"""

pngmath_latex_preamble = ADDITIONAL_PREAMBLE

#\newcommand{\Vx}{\boldsymbol{x}}
#\input{preamble._tex}
latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
'papersize': 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
'preamble': ADDITIONAL_PREAMBLE,
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'FFTHomPy.tex', u'FFTHomPy Documentation',
   u'Jaroslav Vondřejc', 'manual'),
]

#latex_additional_files = ['latex/commands.tex']

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []




# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'ffthompy', u'FFTHomPy Documentation',
     [u'Jaroslav Vondřejc'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'FFTHomPy', u'FFTHomPy Documentation',
   u'Jaroslav Vondřejc', 'FFTHomPy', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False
